### ISSUE TITLE
Minor, but confusing: GPS Epoch should be 6th of January 1980, not 1970.

### ISSUE THREAD

**Issue by ncasaril** [Lora-net/lr1110_evk_demo_app#6]
See here: 

https://github.com/Lora-net/lr1110_evk/blob/e3625deaad446679d7ceeed6c6213424a5b77a39/embedded/demo/src/demo_gnss_base.cpp#L447

**Comment by matthieuantoine** [comment]
Thanks for reporting this! We will update the comment for the next release.

**Comment by matthieuantoine** [comment]
Fixed in release v2.0.0 - see:

- https://github.com/Lora-net/lr1110_evk_demo_app/blob/458decb6089935b738d5ca4af92654fcb7426471/embedded/demo/inc/demo_modem_gnss_interface.h#L91
- https://github.com/Lora-net/lr1110_evk_demo_app/blob/458decb6089935b738d5ca4af92654fcb7426471/embedded/demo/inc/demo_transceiver_gnss_interface.h#L94
